stages:
  - build
  - test
  - deploy

variables:
  DJANGO_SETTINGS_MODULE: "MuslimLife.settings"
  HEROKU_APP_NAME: "muslim-life"

before_script:
  - apt-get update -y && apt-get install -y python3-pip
  - pip3 install -r requirements.txt

build-job:
  stage: build
  script:
    - echo "Collecting static files..."
    - python manage.py collectstatic --noinput

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - python manage.py test

lint-test-job:
  stage: test
  script:
    - echo "Linting code..."
    - pylint prayer_times islamic_calendar quran nlp_quran homepage # Adjust to your app names

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application to Heroku..."
    - apt-get install -y heroku
    - heroku login -i
    - git push heroku master
