# Generated by Django 4.2.3 on 2023-07-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islamic_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='islamicevent',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='islamicevent',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='event_pictures/'),
        ),
    ]
