# Generated by Django 4.2.3 on 2023-07-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('islamic_calendar', '0002_islamicevent_description_islamicevent_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='islamicevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='islamicevent',
            name='picture',
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='event_pictures/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islamic_calendar.islamicevent')),
            ],
        ),
    ]
