name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --deploy --ignore-pipfile

      - name: Collect static files
        run: pipenv run python manage.py collectstatic --noinput

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Heroku CLI
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version
          docker login --username=_ --password="${HEROKU_API_KEY}" registry.heroku.com

      - name: Build and push Docker image
        run: |
          docker build -t registry.heroku.com/muslim-life/web .
          docker push registry.heroku.com/muslim-life/web

      - name: Release Docker image
        run: heroku container:release -a muslim-life
